    <dict>
      <key>begin</key>
      <string>^(\s*)(coffee):$</string>
      <key>beginCaptures</key>
      <dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>constant.language.name.coffeescript.filter.slim</string>
        </dict>
      </dict>
      <key>end</key>
      <string>^(?!(\1\s)|\s*$)</string>
      <key>name</key>
      <string>text.coffeescript.filter.slim</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>source.coffee</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>begin</key>
      <string>^(\s*)(javascript):$</string>
      <key>beginCaptures</key>
      <dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>constant.language.name.javascript.filter.slim</string>
        </dict>
      </dict>
      <key>end</key>
      <string>^(?!(\1\s)|\s*$)</string>
      <key>name</key>
      <string>text.javascript.filter.slim</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>source.js</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>begin</key>
      <string>^(\s*)(styl):$</string>
      <key>beginCaptures</key>
      <dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>constant.language.name.stylus.filter.slim</string>
        </dict>
      </dict>
      <key>end</key>
      <string>^(?!(\1\s)|\s*$)</string>
      <key>name</key>
      <string>text.stylus.filter.slim</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>source.stylus</string>
        </dict>
      </array>
    </dict>
